name = "pratibha"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { NODE_ENV = "production", OTP_CODE_LENGTH = "6", OTP_TOKEN_EXPIRY = "600", SETUP_TOKEN_EXPIRY = "3600" }

[[env.production.secrets]]
name = "DATABASE_URL"

[[env.production.secrets]]
name = "NEXTAUTH_SECRET"

[[env.production.secrets]]
name = "NEXT_PUBLIC_API_URL"

[[env.production.secrets]]
name = "NEXT_PUBLIC_APP_URL"

[[env.production.secrets]]
name = "NEXT_PUBLIC_SITE_URL"

[[env.production.secrets]]
name = "R2_ACCESS_KEY_ID"

[[env.production.secrets]]
name = "R2_SECRET_ACCESS_KEY"

[[env.production.secrets]]
name = "R2_BUCKET_NAME"

[[env.production.secrets]]
name = "R2_ENDPOINT"

[[env.production.secrets]]
name = "R2_PUBLIC_URL"

[[env.production.secrets]]
name = "AWS_REGION"

[[env.production.secrets]]
name = "FACEBOOK_APP_ID"

[[env.production.secrets]]
name = "FACEBOOK_APP_SECRET"

[[env.production.secrets]]
name = "RAZORPAY_KEY_ID"

[[env.production.secrets]]
name = "RAZORPAY_KEY_SECRET"

[[env.production.secrets]]
name = "RESEND_API_KEY"

[[env.production.secrets]]
name = "RESEND_FROM_EMAIL"

[[env.production.secrets]]
name = "TELEGRAM_BOT_TOKEN"

[[env.production.secrets]]
name = "TWILIO_ACCOUNT_SID"

[[env.production.secrets]]
name = "CRON_SECRET"
